### ISSUE TITLE
Can't deploy on SASjs server on windows

### ISSUE THREAD

**Issue by VladislavParhomchik** [sasjs/minimal-seed-app#17]
This happens on minimal-seed-app on appinit:
![image](https://user-images.githubusercontent.com/83717836/170451421-016ffd62-5397-4bc3-8cfa-1dddc805b894.png)

SAS log:
https://paste.4gl.io/?e8210ae9c27f2e81#DWz7WVMhm6ArVXyXmdxSd1DHRmFC7VoGGS11veGzAXuw

**Comment by allanbowe** [comment]
Closing following internal investigation
